server:
  port: 8009
spring:
  datasource:
    url: jdbc:mysql://150.158.76.169:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Alexwong1998.