server:
  port: 8009
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo_database?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
  servlet:
    multipart:
      max-file-size: 40960MB
      max-request-size: 40960MB
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0